version: '3.1'

services:
  mysql_db:
    container_name: mysql
    image: mysql:8.4.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /home/alex/mysql/dbdata:/var/lib/mysql/
