filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
filebeat.modules:
  - module: nginx
    access:
      var.paths: ["/var/log/nginx/access.log*"] 

output.elasticsearch:
  enabled: true
  hosts: ["elasticsearch:9200"] 