version: '3.7'

services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.io/library/elasticsearch:7.17.23
    container_name: elasticsearch
    environment:
      - cluster.name=es-neto-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.io/library/kibana:7.17.23
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
    image: elastic/filebeat:7.17.23
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    command: --strict.perms=false
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - elasticsearch
    volumes:
      #- nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
volumes:
  elasticsearch-data:
    driver: local