version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=12345
      - RABBITMQ_NODE_PORT=5672
    volumes:
      - ./config:/config
      - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    ports:
      - 15672:15672
      - 5672:5672